lightout: clean File.o Proof.o Solver.o lightout.o
	g++ -o $@ -std=c++11 -g File.o Proof.o Solver.o lightout.o

File.o: File.cpp
	g++ -c -std=c++11 -g File.cpp

Proof.o: Proof.cpp
	g++ -c -std=c++11 -g Proof.cpp

Solve.o: Solver.cpp
	g++ -c -std=c++11 -g Solver.cpp

lightout.o: lightout.cpp
	g++ -c -std=c++11 -g lightout.cpp

clean:
	rm -f *.o satTest tags
